# Per-VM sops-nix configuration (guest side).
# Imported into the VM config when vm.sops.enable = true.
#
# Secrets decrypt with two identities: the post-quantum age key provisioned on
# the host for this VM (forest/secrets/host.nix) and the SSH host key
# (ssh-to-age). Both are mounted in via the host-keys share. Get the PQ public
# recipient with `forest pubkey <vm>` and add it to your .sops.yaml.
{ sopsNixSrc, defaultSopsFile }:
{
  imports = [ "${sopsNixSrc}/modules/sops" ];

  fileSystems."/var/lib/host-keys".neededForBoot = true;

  # Two decryption identities, so a secret can be encrypted to either recipient:
  #   - keyFile: the host-provisioned post-quantum age key (age-keygen -pq),
  #     handed out by `forest pubkey <vm>`. generateKey = false — the host owns
  #     key creation, sops-install-secrets must not mint its own here.
  #   - sshKeyPaths: the SSH host key, ssh-to-age-converted (this is also the
  #     sops-nix default for an openssh host). Keeps the classic recipient
  #     working alongside the PQ one.
  # sops-install-secrets loads all of these and decrypts with whichever matches.
  sops.age.keyFile = "/var/lib/host-keys/age-pq.key";
  sops.age.generateKey = false;

  # We also allow decrypting secrets with the SSH host key generated by `openssh`,
  # but this should not be considered part of the stable interface and may be
  # removed in a future update.
  # Got a reason to need this long-term? Open an issue and tell us about it.
  sops.age.sshKeyPaths = [ "/var/lib/host-keys/ssh_host_ed25519_key" ];

  sops.defaultSopsFile = defaultSopsFile;
}
